//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CESistemaVenta.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CasoEstudioSistemaVentasEntities : DbContext
    {
        public CasoEstudioSistemaVentasEntities()
            : base("name=CasoEstudioSistemaVentasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Almacen> Almacen { get; set; }
        public virtual DbSet<AlmacenProducto> AlmacenProducto { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<DetalleVenta> DetalleVenta { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<Juridico> Juridico { get; set; }
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<Natural> Natural { get; set; }
        public virtual DbSet<PaisProcedencia> PaisProcedencia { get; set; }
        public virtual DbSet<Precio> Precio { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Venta> Venta { get; set; }
    }
}
